export { default as Home } from './Home';
export { default as Products } from './Products';
export { default as Product } from './Product';
export { default as AboutPage } from './AboutPage';
export { default as ContactPage } from './ContactPage';
export { default as Cart } from './Cart';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Checkout } from './Checkout';
export { default as PageNotFound } from './PageNotFound';
// export {default as Profile } from './Profile';
export {default as ShowUserDetails } from './Users/ShowsUserDetails';
export {default as UpdateUserDetails } from './Users/UpdateUserDetails';
export {default as CreateUserDetails } from './Users/CreateUserDetails';
